# Generated by Django 4.1 on 2022-09-27 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todolist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name=datetime.datetime.now),
        ),
    ]
